// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALRrOskikCu_7kruoNMOycNLBI77cane4',
    appId: '1:338642023579:web:d68f9b656beadfc45f023e',
    messagingSenderId: '338642023579',
    projectId: 'tubesmobile-88d75',
    authDomain: 'tubesmobile-88d75.firebaseapp.com',
    storageBucket: 'tubesmobile-88d75.firebasestorage.app',
    measurementId: 'G-ZMWTCE2RR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhUVCcx1M-_kBKPKgWoqToHgFUNY4AKFY',
    appId: '1:338642023579:android:de2cfe67c29a52105f023e',
    messagingSenderId: '338642023579',
    projectId: 'tubesmobile-88d75',
    storageBucket: 'tubesmobile-88d75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXLV1ylZazK7ezSA5Hz-AP6P_jH1Q_K0Y',
    appId: '1:338642023579:ios:64f58c2606f6de445f023e',
    messagingSenderId: '338642023579',
    projectId: 'tubesmobile-88d75',
    storageBucket: 'tubesmobile-88d75.firebasestorage.app',
    iosBundleId: 'com.example.tubes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXLV1ylZazK7ezSA5Hz-AP6P_jH1Q_K0Y',
    appId: '1:338642023579:ios:64f58c2606f6de445f023e',
    messagingSenderId: '338642023579',
    projectId: 'tubesmobile-88d75',
    storageBucket: 'tubesmobile-88d75.firebasestorage.app',
    iosBundleId: 'com.example.tubes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALRrOskikCu_7kruoNMOycNLBI77cane4',
    appId: '1:338642023579:web:b1404c128cdd14a65f023e',
    messagingSenderId: '338642023579',
    projectId: 'tubesmobile-88d75',
    authDomain: 'tubesmobile-88d75.firebaseapp.com',
    storageBucket: 'tubesmobile-88d75.firebasestorage.app',
    measurementId: 'G-DH9NTN9Q1M',
  );
}
